spring:
  application:
    name: consumer-demo
  cloud:
    consul:
      discovery:
        health-check-path: /actuator/health
        health-check-interval: 10s
        tags: consumer
        metadata: {"name":"consumer","key":"zxd-test"}
#        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#        datacenters:
#          consul-demo: dc1
        serviceName: ${spring.application.name}
        register: true
        hostname: 192.168.10.73 #配置 Spring Boot服务的主机地址，也可以不进行配置，默认本机地址
server:
  port: 8090
